

(sip-data-classification-py3.13) (base) illikan@illikan-VirtualBox:~/Coding/Vesnin/SIP_Data_classification$ poetry run python app.py
Traceback (most recent call last):
  File "/home/illikan/Coding/Vesnin/SIP_Data_classification/app.py", line 6, in <module>
    import data_processing
  File "/home/illikan/Coding/Vesnin/SIP_Data_classification/data_processing.py", line 15, in <module>
    import s2geometry as s2
  File "/home/illikan/.cache/pypoetry/virtualenvs/sip-data-classification-dJgYZQSF-py3.13/lib/python3.13/site-packages/s2geometry/__init__.py", line 1, in <module>
    from .pywraps2 import *
  File "/home/illikan/.cache/pypoetry/virtualenvs/sip-data-classification-dJgYZQSF-py3.13/lib/python3.13/site-packages/s2geometry/pywraps2.py", line 10, in <module>
    from . import _pywraps2
ImportError: /home/illikan/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/illikan/.cache/pypoetry/virtualenvs/sip-data-classification-dJgYZQSF-py3.13/lib/python3.13/site-packages/s2geometry/_pywraps2.so)

ldd /home/illikan/.cache/pypoetry/virtualenvs/sip-data-classification-dJgYZQSF-py3.13/lib/python3.13/site-packages/s2geometry/_pywraps2.so

 libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x0000765ad1400000)

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_3.4.31
GLIBCXX_3.4.32
GLIBCXX_3.4.33
